swagger: '2.0'
info:
  version: 2.0.0
  title: Fana Protocol API
  description: Api to scrap any Telegram channels

schemes:
  - http
host: localhost:2000
basePath: /api/

paths:
  /get_info/{channel}:
    get:
      description: Returns Object Of Channel Infrmations
      parameters:
        - name: channel
          in: path
          description: Example @Shopchannel
          type: string
          required: true
      responses:
        200:
          description: Returns Object of properties
          schema:
            type: object
            properties:
              profile:
                type: string
              title:
                type: string
              username:
                type: string
              subscribers:
                type: string
              photos:
                type: string
              links:
                type: string

  /get_post/{channel}:
    get:
      description: Returns The latest channel posts available
      parameters:
        - name: channel
          in: path
          description: Example @worldbooks
          type: string
          required: true
        - name: after
          in: query
          description: Example after=122
          type: string
        - name: before
          in: query
          description: Example before=122
          type: string
      responses:
        '200':
          description: Returns Objects... of Array
          schema:
            $ref: '#/definitions/MyArray'

  /channel_value/{channel}:
    get:
      description: Returns latest posts of channels list
      parameters:
        - name: 'channel'
          in: 'path'
          description: Example @Shopchannel
          type: string
          required: true
        - name: after
          in: query
          description: Example after=1200
          type: string
        - name: before
          in: query
          description: Example before=1200
          type: string
      responses:
        200:
          description: Array of Objects...
          schema:
            $ref: '#/definitions/ChennelValue'

  /getlastpost_id/{channel}:
    get:
      description: Returns post id of last channel post
      parameters:
        - name: 'channel'
          in: 'path'
          description: Example @Shopchannel
          type: string
          required: true
      responses:
        '200':
          description: Returns Object of property last_post_id
          schema:
            type: object
            properties:
              last_post_id:
                type: string

  /getpostby_id/{channel}/{id}:
    get:
      description: Returns single post Object by id
      parameters:
        - name: 'channel'
          in: 'path'
          description: Example @Shopchannel
          type: string
          required: true
        - name: 'id'
          in: path
          description: Example 444
          type: integer
          required: true
      responses:
        '200':
          description: Array Of Object
          schema:
            type: array
            items:
              type: object
              properties:
                img:
                  type: string
                id:
                  type: integer
                description:
                  type: string

  /getmultiplechannels_post:
    get:
      description: Returns Array of Array of channel post properties << [ [ {...} ] ] >>, takes more than 1 channel
      parameters:
        - name: channel1
          in: 'query'
          description: Example @Shopchannel
          type: string
          required: true
        - name: channel2
          in: query
          description: Example @worldbooks
          type: integer
          required: true
      responses:
        200:
          description: Array of Array of Objects << [ [ {...} ] ] >>
          schema:
            type: array
            items:
              type: array
              items:
                type: object
                properties:
                  img:
                    type: string
                  id:
                    type: integer
                  description:
                    type: string

definitions:
  ChennelValue:
    type: array
    items:
      $ref: '#/definitions/ChennelValueObj'
    example:
      - img: 'https...'
        scraped_id: 123
        description: 'Post ....'
        price: '3400'
        phone: '+2519 ...'
      - img: 'https...'
        scraped_id: 123
        description: 'Post ....'
        price: '3400'
        phone: '+2519 ...'
  ChennelValueObj:
    type: object
    properties:
      img:
        type: string
      scraped_id:
        type: integer
      description:
        type: string
      price:
        type: string
      phone:
        type: string

  MyArray:
    type: array
    items:
      $ref: '#/definitions/Myobjects'
    example:
      - img: 'https...'
        id: 123
        text: 'Post ....'
      - img: 'https...'
        id: 134
        text: 'Post ....'
  Myobjects:
    type: object
    properties:
      img:
        type: string
      id:
        type: string
      text:
        type: string
